Refactoring frontend
amosproj/amos2022ss04-digital-identity pull request #133
Opened 2022-06-10 21:29 UTC by annikakrause

Finished #93. Changed folder structure, added service for http requests, refactored the code, used prettier.
Done by @valentinBraeutigam and @annikakrause.

RM: @steve-237

2022-06-10 23:04 UTC, Idontker requested changes
**Dateisystem**:
- [x] pages: 
  - [x] nicht einheitlich benannt. pages sollten einheitlich auf "example-page" enden
    - [x] home ~> home-page
    - [x] schema-overview ~> schema-overview-page
    - [x] DI-Overview ~> DIOverview-page
  - [x] settings component wird nirgends genutzt und beinhaltet nichts als boilerplate code
- [x] shared: ggf. shared/pop-up/ erstellen

**Sonstiges**:
- [ ] navigation-bar.component.html: großer aus kommentierter Block. Ist der noch relevant? 
- [ ] Man kann sich überlegen, einzelne Services für die einzelnen Anfragen zu erstellen. (Diese können gerne auf den aktuellen Serivce verweisen). Idee dabei wäre einfach, dass die Components weniger Aufgaben besitzen würden. Kp, ob es das übersichtlicher macht.

2022-06-11 16:36 UTC, annikakrause commented on src/digitalIdentity-frontend/src/app/components/navigation-bar/navigation-bar.component.html
>    <nav mat-tab-nav-bar mat-align-tabs="center">
@steve-237 brauchst du den Block noch in navigation-bar oder kann ich den löschen?

2022-06-11 17:01 UTC, annikakrause commented on src/digitalIdentity-frontend/src/app/pages/DI/DI-Overview/DI-Overview.component.ts
> +      .catch((response) => {
Frontend Fehlermeldungen sind explizit nicht Teil dieses issues (war auch so besprochen).

2022-06-11 17:04 UTC, annikakrause commented
Ein einziger Service für http request ist sinnvoll, das würde ich nicht auftrennen (letzter Punkt unter "Sonstiges"). Der Rest ist erledigt.

2022-06-11 17:49 UTC, Idontker commented on src/digitalIdentity-backend/src/test/java/didentity/amos/digitalIdentity/Services/LissiApiServiceTest.java
> +package didentity.amos.digitalIdentity.Services;
packages shall be lowercased. If this leads to an error, please fix your path

2022-06-11 17:51 UTC, Idontker approved these changes

2022-06-11 17:51 UTC, merged

2022-06-11 18:43 UTC, steve-237 commented on src/digitalIdentity-frontend/src/app/components/navigation-bar/navigation-bar.component.html
>    <nav mat-tab-nav-bar mat-align-tabs="center">
Nein brauche ich das nicht mehr