Moved responses from model to responses
amosproj/amos2022ss04-digital-identity pull request #219
Opened 2022-07-01 15:42 UTC by jackDS008

Signed-off-by: Jannik Kiesel <jannik.kiesel@fau.de>

Die Bezeichnung "Content" würde ich erstmal so lassen, da sie im JSON auch so steht. Wenn es später mehrere Contents mal geben wird, dann sollten wir uns überlegen Unterordner zu erstellen oder doch über eine Umbenennung nachdenken.

2022-07-02 10:24 UTC, Idontker requested changes
Ich würde Content dringlichst umbenennen. Es gibt einige Anfragen, die ein Attribut namens Content zurücksenden. 
Vergleiche hierzu meine branch für die Woche: [https://github.com/amosproj/amos2022ss04-digital-identity/tree/173-retrieve-credential-log](https://github.com/amosproj/amos2022ss04-digital-identity/tree/173-retrieve-credential-log)

2022-07-02 11:01 UTC, jackDS008 commented
@Idontker 

Ich bin da dagegen. Das JsonProperty muss Content heißen, deshalb sollte die Klasse auch Content heißen
```
@JsonProperty("content")
```
Allerdings finde ich es sinnvoll die Klasse in einen neuen Ordner "Connection" im Ordner Model zu verschieben. Siehe Änderung.

Gerne können wir auch bei verschiedenen Meinungen das mit dem gesamten Team besprechen. Ich denke die Lösung mit dem Unterordner ist aber ein guter Kompromiss.

2022-07-03 10:03 UTC, Idontker commented
Zu deinem PR:
Bin bisschen verwirrt, warum du eine Lösung wie in meinem Branch ist ablehnst. 
Einerseits ist der Klassenname doch nicht relevant für das json. Die Annotation kümmert sich ja um das verbinden der json Bezeichnung und des Attributs. Also muss der Klassenname nicht Content heißen. Und klar, könnten wir es über Unterordner machen. Aber dann muss du jedes mal, wenn du die Klasse Content importierst, darauf achten, dass du es aus dem richtigen Package kommt. Finde ich persönlich schwierig. 
Weiter würde man dadurch duplizierten Code haben, den man durch Generics doch super lösen kann. 

Ich sehe gerade bei deinen Vorschlägen einige Gefahren/Probleme und keine Notwendigkeit es so zu bauen ^^"

2022-07-03 11:42 UTC, jackDS008 commented
@Idontker Ich habe Content nun zu ConnectionContent umbenannt. Bitte um Review und ggf. merge

2022-07-03 14:46 UTC, Idontker approved these changes

2022-07-03 14:46 UTC, merged