240 filter for di on detailed overview of one proof
amosproj/amos2022ss04-digital-identity pull request #279
Opened 2022-07-17 16:26 UTC by steve-237

Added Proofs filter and tests

RM : @Jean28518

2022-07-18 23:10 UTC, jackDS008 requested changes
Leider konnte ich bei keinem Proof die Attribute einsehen. Sie waren immer leer. Liegt dies daran, dass keine Attribute vorhanden sind oder dass die Logik (noch) nicht funktioniert?

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-activities/proof-activities.component.ts
> +          }
Was willst du hier mit den if-Statements abfragen?

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +    let event = { target: { value: 'Jannik 20220620' } };
Bitte keine echten Werte hart codieren. Diese werden im Realbetrieb nicht mehr auf der Datenbank sein. Hier nur Dummy-Werte (ohne meinen Namen bitte)

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      state: 'REQUEST_SENT',
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      state: 'REQUEST_SENT',
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      state: 'REQUEST_SENT',
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      state: 'REQUEST_SENT',
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      state: 'REQUEST_SENT',
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      'GCevMyEWCa5Fd58gfzkASy:3:CL:8768:Mitarbeiter Ausweis Adorsys': {
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      'http://onboardingad.ddns.net/ctrl/images/download/c06718a9-8866-456f-99cc-8e6b504048d3',
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +    state: 'REQUEST_SENT',
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      'GCevMyEWCa5Fd58gfzkASy:3:CL:8768:Mitarbeiter Ausweis Adorsys': {
Hier auch nur Dummy-Werte bitte

2022-07-18 23:10 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +      'GCevMyEWCa5Fd58gfzkASy:3:CL:8768:Mitarbeiter Ausweis Dauerhaft': {
Hier auch nur Dummy-Werte bitte

2022-07-19 14:59 UTC, steve-237 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-activities/proof-activities.component.ts
> +          }
Dies soll mir versichern, dass diese Variablen Werte haben, und dies ist nützlich, damit ein Testfall gut funktioniert, ohne dass der Test fehlschlägt.

2022-07-19 15:00 UTC, steve-237 commented on src/digitalIdentity-frontend/src/app/components/proof-detail/proof-detail-pop-up/proof-detail-pop-up.component.spec.ts
> +    let event = { target: { value: 'Jannik 20220620' } };
Sorry! Das ändere ich gleich

2022-07-19 15:02 UTC, steve-237 commented
> Leider konnte ich bei keinem Proof die Attribute einsehen. Sie waren immer leer. Liegt dies daran, dass keine Attribute vorhanden sind oder dass die Logik (noch) nicht funktioniert?

Ich denke, es liegt daran, dass es keine Attribute gibt

2022-07-19 16:56 UTC, merged