267 pop up windows according to mockup
amosproj/amos2022ss04-digital-identity pull request #281
Opened 2022-07-17 21:51 UTC by steve-237

Pop up information windows according to mockup

RM : @Jean28518

2022-07-18 18:42 UTC, jackDS008 commented
Beim Delete einer Connection wird ein Text nicht richtig angezeigt:

```
Are you sure to delete the DI with email ...?
```

![image](https://user-images.githubusercontent.com/93184461/179580375-fd197b1c-705c-4690-8c66-5282b104ec35.png)

2022-07-18 18:45 UTC, jackDS008 commented
Die restlichen Pop up windows schauen gut aus :)

2022-07-18 18:49 UTC, jackDS008 commented on src/digitalIdentity-frontend/src/app/shared/pop-up/information-pop-up/information-pop-up.component.html
> +<div class="container">
Bitte noch beim schemas details schauen, warum es nicht richtig angezeigt wird und anpassen.

2022-07-18 18:49 UTC, jackDS008 requested changes
Bitte noch beim schemas details schauen, warum es nicht richtig angezeigt wird und anpassen.

2022-07-18 19:04 UTC, steve-237 commented
> Beim Delete einer Connection wird ein Text nicht richtig angezeigt:
> 
> ```
> Are you sure to delete the DI with email ...?
> ```
> 
> ![image](https://user-images.githubusercontent.com/93184461/179580375-fd197b1c-705c-4690-8c66-5282b104ec35.png)


Für diese Aufgabe musste ich nur am Komponenten Popup-Information arbeiten und den Stil anwenden, der sich im Modell befindet. Der Stil für dieses Popup ist meines Erachtens nicht Teil dieser Ausgabe. Es sei denn, ich liege falsch.

2022-07-18 19:07 UTC, steve-237 commented
> Was ist dieses rote X beim Details von schemas? Ist etwas groß und der Nutzer kann nicht erkennen, was dessen Bedeutung ist.
> 
> ![image](https://user-images.githubusercontent.com/93184461/179580801-fa02fc06-5e37-41e9-b4b6-817e92097ccb.png)

Dieses Popup muss geändert werden, um die Details zu einem Schema anzuzeigen, deshalb habe ich es nicht geändert

2022-07-18 23:37 UTC, jackDS008 commented
Okay, kann es sein, dass diese zwei Windows durch deine Änderungen beeinflusst werden, du das aber garnicht willst? Im main schauen die pop ups nämlich anders aus

2022-07-19 14:55 UTC, steve-237 commented
> Okay, kann es sein, dass diese zwei Windows durch deine Änderungen beeinflusst werden, du das aber garnicht willst? Im main schauen die pop ups nämlich anders aus

Für das erste Fenster glaube ich nicht, aber für das zweite ist es normal, da dieses Popup derzeit die Informations-Popup-Komponente verwendet und diese soll geändert werden, um stattdessen Details eines Schemas anzuzeigen, und wird eine andere Komponente verwenden
![Capture d’écran 2022-07-19 154603](https://user-images.githubusercontent.com/88513912/179781210-913d40d9-465b-483c-9d43-7afa93ccd34b.png)
.
Ich bin gerade auf dem Main Branch und der Text kann auch da nicht gelesen werden

2022-07-19 16:56 UTC, merged